PATCH https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/653
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Ugly buttons"
}

###