PATCH https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/653
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Ugly buttons"
}

<> 2019-05-18T043429.200.json

###

PATCH https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/653
Content-Type: application/json

{
  "title": "Ugly buttons"
}

<> 2019-05-18T043314.401.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T023734.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T022145.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": [
    "golqm kur"
  ]
}

<> 2019-05-18T020619.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": [
    "enchancement"
  ]
}

<> 2019-05-18T020556.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": [
    "enchancement",
    "major"
  ]
}

<> 2019-05-18T020533.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T020300.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T020232.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T020116.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODg

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T020108.401.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T020054.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json
Authorization: Basic dmlsaWV2a29mYXRhOlBlcnNvbmFsIE5vOiAwMzUyMDU2ODgx

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T020047.201.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json

{
  "title": "Cooler buttons",
  "body": "Pesho wants cooler buttons!",
  "labels": ["enchancement", "major"]
}

<> 2019-05-18T015951.404.json

###

POST https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues
Content-Type: application/json

{}

<> 2019-05-18T115450.404.json

###

GET http://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/1
Host: api.github.com

<> 2019-05-18T111340.200.json

###

GET http://repos/SoftUni-Tech-Module/TestRepository/issues/1
Host: api.github.com

###

GET http://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/1
Host: api.github.com

<> 2019-05-18T111230.200.json

###

GET https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/1

<> 2019-05-18T110824.200.json

###

GET https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/1

<> 2019-05-18T110730.200.json

###

GET https://api.github.com/repos/SoftUni-Tech-Module/TestRepository/issues/1

<> 2019-05-18T110616.200.json

###

GET https://api.github.com/users/SoftUni-Tech-Module/repos

<> 2019-05-18T110247.200.json

###

GET http://htts

###

GET https://api.github.com/users/SoftUni-Tech-Module/repos

<> 2019-05-18T104412.200.json

###

GET https://api.github.com/users/SoftUni-Tech-Module/repos

<> 2019-05-18T104347.200.json

###

GET https://api.github.com/users/SoftUni-Tech-Module/repos
Accept: application/json

<> 2019-05-18T104303.200.json

###

